name: Go

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:  # 设置环境变量
      USER: ${{ secrets.USER }}
      PASS: ${{ secrets.PASS }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Get dependencies
      run: go get -u
    - name: Run
      run: go run main.go
